=== rpindel/csd-430/mod9XMLs/pokemonXMLSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
<xs:element name="pokedex">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="pokemon" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="number" type="xs:string" maxOccurs="unbounded"/>
						<xs:element name="name" type="xs:string" maxOccurs="unbounded"/>
						<xs:element name="type-1" type="xs:string" maxOccurs="unbounded"/>
						<xs:element name="type-2" type="xs:string" maxOccurs="unbounded"/>
						<xs:element name="home-region" type="xs:string" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="evolution-line" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== rpindel/csd-430/mod9XMLs/pokemonXMLExternalSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="mod9.css"?>

<pokedex
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="pokemonXMLSchema.xsd">
	<pokemon evolution-line="charmander">
		<number>0004</number>
		<name>Charmander</name>
		<type-1>Fire</type-1>
		<type-2>None</type-2>
		<home-region>Kanto</home-region>
	</pokemon>
	<pokemon evolution-line="charmander">
		<number>0005</number>
		<name>Charmeleon</name>
		<type-1>Fire</type-1>
		<type-2>None</type-2>
		<home-region>Kanto</home-region>
	</pokemon>
	<pokemon evolution-line="charmander">
		<number>0006</number>
		<name>Charizard</name>
		<type-1>Fire</type-1>
		<type-2>Flying</type-2>
		<home-region>Kanto</home-region>
	</pokemon>
</pokedex>
